# Introduction

In [1]:
import numpy as np
import pandas as pd

# Data Science Packages
import sys
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from  matplotlib import pyplot
import seaborn as sns
import warnings
# Seaborn Style
sns.set(style='ticks')
sns.set_style({'font.family': 'Hiragino Maru Gothic Pro'})
sns.set_palette("cool")

# Pandas Style
pd.set_option("display.max_column", 9999)
pd.set_option("display.max_row", 9999)

# Ignore annoying warning 
warnings.filterwarnings('ignore')

## 1. Load all data

In [ ]:
dfl = pd.read_parquet(path+'/list_asset_ids_without_tickets_onefile.parquet')
print(dfl.shape)
dfl.head()

### 1.1 For HA35-11

In [2]:
path = '/Users/vikaschaturvedi/Documents/TCON/predictive_care/DSL_lines/preprocessed_data/'

Healthy data

In [195]:
dfl = pd.read_parquet(path+'/list_asset_ids_without_tickets_onefile.parquet')
print(dfl.shape)
dfl.head()

(387642, 2)


asset_id        date
0   85024268  2020-08-15
1   50361321  2020-11-26
2   48864041  2020-08-17
3  117157278  2021-03-22
4   28966858  2021-03-17

In [201]:
dfl.dropna(inplace=True)

In [202]:
dfl['asset_id'] =dfl['asset_id'].astype('int')

In [203]:
dfl1 = dfl.merge(df_healthy[['assetid']],left_on='asset_id',right_on='assetid',how='inner')
dfl1.shape

(14830, 3)

In [204]:
dfl1.head()

asset_id        date   assetid
0  45683801  2021-03-21  45683801
1  45683801  2020-10-04  45683801
2  41252192  2020-06-23  41252192
3  28392257  2020-07-01  28392257
4  35794131  2020-06-12  35794131

In [205]:
dfl1.rename(columns={'date':'incident_date'},inplace=True)
dfl1 = dfl1[['assetid','incident_date']]
dfl1.to_parquet(path+'helthy_ha35_seq_date.parquet')

In [206]:
dfl1.to_csv(path+'helthy_ha35_seq_date.csv',index=False)

In [3]:
df_healthy = pd.read_parquet(path+'/HA35/ha_35_healthy.parquet')
print(df_healthy.shape)
df_healthy.head()

(14961, 681)


assetid  avg_dslam_code_of_dominant_modulation_32days  \
0   8613560                                           3.0   
1  19681213                                           3.0   
2  28826517                                           3.0   
3  32263794                                           6.0   
4  32283656                                           3.0   

   max_dslam_code_of_dominant_modulation_32days  \
0                                           3.0   
1                                           3.0   
2                                           3.0   
3                                           6.0   
4                                           3.0   

   min_dslam_code_of_dominant_modulation_32days  \
0                                           3.0   
1                                           3.0   
2                                           3.0   
3                                           6.0   
4                                           3.0   

   avg_dslam_avg_bitrate_us_32days  max_dslam_avg_bitrate_us_32days  \
0                            647.0                            647.0   
1                            829.0                            829.0   
2                            837.0                            837.0   
3                           1256.0                           1256.0   
4                           1093.0                           1093.0   

   min_dslam_avg_bitrate_us_32days  avg_dslam_avg_bitrate_ds_32days  \
0                            647.0                      4935.000000   
1                            829.0                      8903.000000   
2                            837.0                     12934.454545   
3                           1256.0                     12919.000000   
4                           1093.0                      9205.000000   

   max_dslam_avg_bitrate_ds_32days  min_dslam_avg_bitrate_ds_32days  \
0                           4935.0                           4935.0   
1                           8903.0                           8903.0   
2                          12959.0                          12419.0   
3                          12919.0                          12919.0   
4                           9205.0                           9205.0   

   avg_dslam_avg_attenuation_ds_32days  max_dslam_avg_attenuation_ds_32days  \
0                            26.000000                                 26.0   
1                            40.423077                                 41.0   
2                            30.272727                                 31.0   
3                            25.000000                                 25.0   
4                            28.000000                                 28.0   

   min_dslam_avg_attenuation_ds_32days  avg_dslam_avg_attenuation_us_32days  \
0                                 26.0                                 18.0   
1                                 40.0                                 22.0   
2                                 30.0                                 14.0   
3                                 25.0                                 13.0   
4                                 28.0                                 12.0   

   max_dslam_avg_attenuation_us_32days  min_dslam_avg_attenuation_us_32days  \
0                                 18.0                                 18.0   
1                                 22.0                                 22.0   
2                                 14.0                                 14.0   
3                                 13.0                                 13.0   
4                                 12.0                                 12.0   

   avg_dslam_avg_power_us_32days  max_dslam_avg_power_us_32days  \
0                      -3.730769                           -3.0   
1                      12.000000                           12.0   
2                      12.954545                           13.0   
3                      11.000000                 

Non DSL tickets data

In [4]:
df_non_dsl = pd.read_parquet(path+'/HA35/non_dsl_ha35.parquet')
print(df_non_dsl.shape)
df_non_dsl.head()

(5398, 681)


assetid  avg_dslam_code_of_dominant_modulation_32days  \
0  101141726                                           3.0   
1  113037402                                           7.0   
2   33210485                                           3.0   
3   36443688                                           3.0   
4   42084231                                           3.0   

   max_dslam_code_of_dominant_modulation_32days  \
0                                           3.0   
1                                           7.0   
2                                           3.0   
3                                           3.0   
4                                           3.0   

   min_dslam_code_of_dominant_modulation_32days  \
0                                           3.0   
1                                           7.0   
2                                           3.0   
3                                           3.0   
4                                           3.0   

   avg_dslam_avg_bitrate_us_32days  max_dslam_avg_bitrate_us_32days  \
0                      1082.480000                           1086.0   
1                      4096.000000                           4096.0   
2                       831.000000                            831.0   
3                      1045.000000                           1045.0   
4                       895.333333                           1013.0   

   min_dslam_avg_bitrate_us_32days  avg_dslam_avg_bitrate_ds_32days  \
0                           1074.0                      9157.600000   
1                           4096.0                     33441.000000   
2                            831.0                      8063.000000   
3                           1045.0                     12581.965517   
4                            860.0                      8873.000000   

   max_dslam_avg_bitrate_ds_32days  min_dslam_avg_bitrate_ds_32days  \
0                           9158.0                           9157.0   
1                          33441.0                          33441.0   
2                           8063.0                           8063.0   
3                          12582.0                          12581.0   
4                           9156.0                           8758.0   

   avg_dslam_avg_attenuation_ds_32days  max_dslam_avg_attenuation_ds_32days  \
0                            42.600000                                 43.0   
1                             9.000000                                  9.0   
2                            33.000000                                 33.0   
3                            32.310345                                 33.0   
4                            44.000000                                 44.0   

   min_dslam_avg_attenuation_ds_32days  avg_dslam_avg_attenuation_us_32days  \
0                                 42.0                            23.440000   
1                                  9.0                             4.000000   
2                                 33.0                            15.590909   
3                                 32.0                            14.482759   
4                                 44.0                            22.000000   

   max_dslam_avg_attenuation_us_32days  min_dslam_avg_attenuation_us_32days  \
0                                 24.0                                 23.0   
1                                  4.0                                  4.0   
2                                 16.0                                 15.0   
3                                 15.0                                 14.0   
4                                 22.0                                 22.0   

   avg_dslam_avg_power_us_32days  max_dslam_avg_power_us_32days  \
0                           12.0                           12.0   
1                            9.0                            9.0   
2                           13.0                           13.0   
3                           13.0            

Unhealthy data

In [5]:
df_unhealthy = pd.read_parquet(path+'/HA35/unhealthy_ha35.parquet')
print(df_unhealthy.shape)
df_unhealthy.head()

(11278, 681)


assetid  avg_dslam_code_of_dominant_modulation_32days  \
0  104543174                                           3.0   
1  117797962                                           6.0   
2   28479815                                           3.0   
3   28819755                                           3.0   
4   32720648                                           3.0   

   max_dslam_code_of_dominant_modulation_32days  \
0                                           3.0   
1                                           6.0   
2                                           3.0   
3                                           3.0   
4                                           3.0   

   min_dslam_code_of_dominant_modulation_32days  \
0                                           3.0   
1                                           6.0   
2                                           3.0   
3                                           3.0   
4                                           3.0   

   avg_dslam_avg_bitrate_us_32days  max_dslam_avg_bitrate_us_32days  \
0                       903.000000                            903.0   
1                       545.043478                           1222.0   
2                       327.000000                            327.0   
3                      1084.000000                           1084.0   
4                       201.000000                            201.0   

   min_dslam_avg_bitrate_us_32days  avg_dslam_avg_bitrate_ds_32days  \
0                            903.0                      5191.000000   
1                            305.0                      6650.652174   
2                            327.0                      3581.606061   
3                           1084.0                      9158.000000   
4                            201.0                       553.241379   

   max_dslam_avg_bitrate_ds_32days  min_dslam_avg_bitrate_ds_32days  \
0                           5191.0                           5191.0   
1                          11391.0                           4945.0   
2                           3823.0                           3459.0   
3                           9158.0                           9158.0   
4                            560.0                            535.0   

   avg_dslam_avg_attenuation_ds_32days  max_dslam_avg_attenuation_ds_32days  \
0                            40.696970                                 41.0   
1                            32.304348                                 33.0   
2                            62.727273                                 63.0   
3                            33.650000                                 34.0   
4                            64.862069                                 69.0   

   min_dslam_avg_attenuation_ds_32days  avg_dslam_avg_attenuation_us_32days  \
0                                 40.0                            23.000000   
1                                 30.0                            18.347826   
2                                 62.0                            35.696970   
3                                 33.0                            18.000000   
4                                 63.0                            39.000000   

   max_dslam_avg_attenuation_us_32days  min_dslam_avg_attenuation_us_32days  \
0                                 23.0                                 23.0   
1                                 19.0                                 17.0   
2                                 36.0                                 35.0   
3                                 18.0                                 18.0   
4                                 39.0                                 39.0   

   avg_dslam_avg_power_us_32days  max_dslam_avg_power_us_32days  \
0                       7.272727                            9.0   
1                      10.608696                           11.0   
2                       4.606061                            6.0   
3                      12.000000            

Load DSL tickets data

In [6]:
df_dsl_tickets = pd.read_parquet(path+'/dsl_tickets.parquet')
print(df_dsl_tickets.shape)
df_dsl_tickets.head()

(103705, 4)


assetid        incident_date                label  level
0  100120619  2020-04-15 18:06:04  DSL synchronization      3
1  100400561  2020-10-10 08:27:21  DSL synchronization      2
2  100512401  2020-07-02 17:40:49  DSL synchronization      3
3  100703298  2020-05-11 17:27:30  DSL synchronization      4
4  100828646  2020-04-17 16:33:13  DSL synchronization      3

In [145]:
df_dsl_tickets.level.value_counts()

3    71364
4    16950
2    15391
Name: level, dtype: int64

In [148]:
df_dsl_tickets1 = df_unhealthy[['assetid']].merge(df_dsl_tickets[['assetid','incident_date']],on='assetid',how='left')
print(df_dsl_tickets1.shape)
df_dsl_tickets1.head()

(11278, 2)


assetid        incident_date
0  104543174  2020-03-22 10:54:11
1  117797962  2021-03-27 10:03:20
2   28479815  2020-03-17 10:34:54
3   28819755  2021-03-24 12:32:38
4   32720648  2020-03-26 18:18:11

In [149]:
df_dsl_tickets1.assetid.nunique()

11278

In [150]:
df_dsl_tickets1.to_parquet(path+'/dsl_tickets_ha35.parquet')

Get Level of the issues

In [7]:
df_unhealthy = df_unhealthy.merge(df_dsl_tickets[['assetid','level']],on=['assetid'],how='left')
print(df_unhealthy.shape)

(11278, 682)


In [8]:
df_unhealthy.level.value_counts()/df_unhealthy.shape[0]

3    0.639564
4    0.214666
2    0.145771
Name: level, dtype: float64

In [11]:
#df_unhealthy["level"].replace({2: 1, 3: 2, 4: 3,}, inplace=True)
#df_unhealthy.level.value_counts()/df_unhealthy.shape[0]

Create combined list of healthy & non-DSL and then create target variable

In [9]:
df_comb_healthy = pd.concat([df_healthy,df_non_dsl],axis=0)

#Create Target Variable
df_comb_healthy['level'] = 0
print(df_comb_healthy.shape)


# Create Target Variable for healthy data
df_healthy['level'] = 0


(20359, 682)


Take sample of Unhealthy data to imbalance the dataset

In [10]:
#df_unhealthy['issue'] = 1
df_unhealthy_sample = df_unhealthy.sample(frac=1)
df_unhealthy_sample = df_unhealthy_sample.reset_index()
df_unhealthy_sample.drop('index',axis=1,inplace=True)
print(df_unhealthy_sample.shape)

(11278, 682)


In [11]:
set_cols = list(df_healthy.columns)
df_unhealthy_sample = df_unhealthy_sample[set_cols]

In [12]:
df_unhealthy_sample_3 = df_unhealthy_sample.loc[df_unhealthy_sample.level==3]
df_unhealthy_sample_3.shape

(7213, 682)

Create all combinational datasets

In [21]:
def create_comb_data(df1,df2):
    df = pd.concat([df1,df2],axis=0)
    #Shuffle the dataset
    df = df.sample(frac=1)
    df = df.reset_index()
    df.drop('index',axis=1,inplace=True)
    print('Shape of dataset: ',df.shape)
    return df

In [22]:
#Combined Healthy, Non-DSL & Unhealthy(hnu)
df_comb_hnu = create_comb_data(df_comb_healthy,df_unhealthy_sample)

#Combined Healthy, Non-DSL & Unhealthy,level=3 (hnu_3)
df_comb_hnu_3 = create_comb_data(df_comb_healthy,df_unhealthy_sample_3)

#Combined Healthy & Unhealthy(hu)
df_comb_hu = create_comb_data(df_healthy,df_unhealthy_sample)

#Combined Healthy & Unhealthy,level=3 (hu_3)
df_comb_hu_3 = create_comb_data(df_healthy,df_unhealthy_sample_3)

Shape of dataset:  (31637, 682)
Shape of dataset:  (27572, 682)
Shape of dataset:  (26239, 682)
Shape of dataset:  (22174, 682)


Get the services of the CPEs

In [23]:
servis_healthy = pd.read_parquet(path+'/healthy_services.parquet')
servis_dsl = pd.read_parquet(path+'/dsl_services.parquet')
servis = pd.concat([servis_healthy,servis_dsl])
print(servis.shape)
print(servis.assetid.nunique())
servis.head()

(95049, 4)
95049


assetid                   dslam_servis dslam_platforma        dslam_model
0   2380053  INTERNET-50Mb / 10Mb+IPTVHDTV  HUAWEI SMARTAX            MA5600T
1   8414049            INTERNET-30Mb / 5Mb  HUAWEI SMARTAX            MA5603T
2   8613560           INTERNET-4Mb / 512kb    ERICSSON EDA  EDA SMALL SUBRACK
3  18074840       INTERNET-20Mb / 2Mb+IPTV  HUAWEI SMARTAX            MA5600T
4  18982658                       IPTVHDTV  HUAWEI SMARTAX            MA5600T

In [24]:
servis['IPTV_enabled'] = servis['dslam_servis'].apply(lambda x: 1 if 'IPTV' in x else 0)
servis['VoIP_enabled'] = servis['dslam_servis'].apply(lambda x: 1 if 'VoIP' in x else 0)
servis['Internet_Pack'] = servis['dslam_servis'].apply(lambda x: 1 if 'INTERNET' in x else 0)
servis.head()

assetid                   dslam_servis dslam_platforma        dslam_model  \
0   2380053  INTERNET-50Mb / 10Mb+IPTVHDTV  HUAWEI SMARTAX            MA5600T   
1   8414049            INTERNET-30Mb / 5Mb  HUAWEI SMARTAX            MA5603T   
2   8613560           INTERNET-4Mb / 512kb    ERICSSON EDA  EDA SMALL SUBRACK   
3  18074840       INTERNET-20Mb / 2Mb+IPTV  HUAWEI SMARTAX            MA5600T   
4  18982658                       IPTVHDTV  HUAWEI SMARTAX            MA5600T   

   IPTV_enabled  VoIP_enabled  Internet_Pack  
0             1             0              1  
1             0             0              1  
2             0             0              1  
3             1             0              1  
4             1             0              0

In [116]:
servis.dslam_platforma.value_counts()/servis.shape[0]

HUAWEI SMARTAX    0.868047
ERICSSON EDA      0.131953
Name: dslam_platforma, dtype: float64

In [117]:
servis.dslam_model.value_counts()/servis.shape[0]

MA5600T                0.642679
MA5603T                0.218614
EDA MEDIUM SUBRACK     0.071195
EDA SMALL SUBRACK      0.058307
MA5608T                0.006323
EDA VDSL SUBRACK       0.002430
MA5623A                0.000316
MA5622A                0.000105
EDA UNKNOWN SUBRACK    0.000021
MA5611S-AE08           0.000011
Name: dslam_model, dtype: float64

In [118]:
servis2 = servis.copy()

In [120]:
servis2[['base_servis']+['nr']] = servis['dslam_servis'].str.split("/",expand=True)

In [121]:
servis2.head()

assetid                   dslam_servis dslam_platforma        dslam_model  \
0   2380053  INTERNET-50Mb / 10Mb+IPTVHDTV  HUAWEI SMARTAX            MA5600T   
1   8414049            INTERNET-30Mb / 5Mb  HUAWEI SMARTAX            MA5603T   
2   8613560           INTERNET-4Mb / 512kb    ERICSSON EDA  EDA SMALL SUBRACK   
3  18074840       INTERNET-20Mb / 2Mb+IPTV  HUAWEI SMARTAX            MA5600T   
4  18982658                       IPTVHDTV  HUAWEI SMARTAX            MA5600T   

   IPTV_enabled  VoIP_enabled  Internet_Pack     base_servis              nr  
0             1             0              1  INTERNET-50Mb    10Mb+IPTVHDTV  
1             0             0              1  INTERNET-30Mb              5Mb  
2             0             0              1   INTERNET-4Mb            512kb  
3             1             0              1  INTERNET-20Mb         2Mb+IPTV  
4             1             0              0        IPTVHDTV            None

In [123]:
servis2['base_service'] = servis2['base_servis'].apply(lambda x: x if 'INTERNET' in x else 'unavailable')

In [137]:
servis2['assetid'] = servis2['assetid'].astype('int')

In [142]:
servis21 =  pd.get_dummies(servis2[['assetid','base_service','dslam_platforma']])
servis21.drop(['base_service_unavailable','dslam_platforma_ERICSSON EDA'],axis=1,inplace=True)
print(servis21.shape)
servis21.head()

(95049, 11)


assetid  base_service_INTERNET-100Mb   base_service_INTERNET-10Mb   \
0   2380053                             0                            0   
1   8414049                             0                            0   
2   8613560                             0                            0   
3  18074840                             0                            0   
4  18982658                             0                            0   

   base_service_INTERNET-20Mb   base_service_INTERNET-2Mb   \
0                            0                           0   
1                            0                           0   
2                            0                           0   
3                            1                           0   
4                            0                           0   

   base_service_INTERNET-30Mb   base_service_INTERNET-40Mb   \
0                            0                            0   
1                            1                            0   
2                            0                            0   
3                            0                            0   
4                            0                            0   

   base_service_INTERNET-4Mb   base_service_INTERNET-50Mb   \
0                           0                            1   
1                           0                            0   
2                           1                            0   
3                           0                            0   
4                           0                            0   

   base_service_INTERNET-60Mb   dslam_platforma_HUAWEI SMARTAX  
0                            0                               1  
1                            0                               1  
2                            0                               0  
3                            0                               1  
4                            0                               1

In [155]:
servis3 = servis2.merge(servis21,on='assetid',how='inner')
servis3.shape

(95049, 20)

In [157]:
servis3.drop(['dslam_servis','dslam_platforma','dslam_model','Internet_Pack','base_servis','nr'],axis=1,inplace=True)

Join the services to our combined tables

In [28]:
df_comb_hnu_s = df_comb_hnu.merge(servis[['assetid','IPTV_enabled','VoIP_enabled','Internet_Pack']],on='assetid',how='left')
df_comb_hnu_3_s = df_comb_hu_3.merge(servis[['assetid','IPTV_enabled','VoIP_enabled','Internet_Pack']],on='assetid',how='left')
df_comb_hu_s = df_comb_hu.merge(servis[['assetid','IPTV_enabled','VoIP_enabled','Internet_Pack']],on='assetid',how='left')
df_comb_hu_3_s = df_comb_hu_3.merge(servis[['assetid','IPTV_enabled','VoIP_enabled','Internet_Pack']],on='assetid',how='left')

print(df_comb_hu_3_s.shape)
print(df_comb_hu_3_s.assetid.nunique())

(22174, 685)
22174


In [165]:
df_comb_hu_3_s1 = df_comb_hu_3.merge(servis,on='assetid',how='left')

In [166]:
df_comb_hu_3_s1[['IPTV_enabled']].isnull().sum().sort_values(ascending=False)

IPTV_enabled    0
dtype: int64

In [167]:
df_comb_hu_3_s1[['base_servis']+['nr']] = df_comb_hu_3_s1['dslam_servis'].str.split("/",expand=True)
df_comb_hu_3_s1['base_service'] = df_comb_hu_3_s1['base_servis'].apply(lambda x: x if 'INTERNET' in x else 'unavailable')

In [171]:
df_comb_hu_3_s1[['assetid', 'base_service']].isnull().sum()

assetid         0
base_service    0
dtype: int64

In [173]:
df_comb_hu_3_s1.drop(['dslam_servis','base_servis','nr','dslam_model','Internet_Pack'],axis=1,inplace=True)

In [175]:
df_comb_hu_3_s1['assetid'] = df_comb_hu_3_s1['assetid'].astype('int')
df_comb_hu_3_s1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22174 entries, 0 to 22173
Columns: 686 entries, assetid to base_service
dtypes: float64(667), int64(17), object(2)
memory usage: 116.2+ MB


In [176]:
df_comb_hu_3_s1 =  pd.get_dummies(df_comb_hu_3_s1)
df_comb_hu_3_s1.drop(['base_service_unavailable','dslam_platforma_ERICSSON EDA'],axis=1,inplace=True)
print(df_comb_hu_3_s1.shape)
df_comb_hu_3_s1.head()

(22174, 693)


assetid  avg_dslam_code_of_dominant_modulation_32days  \
0  49021997                                        3.0000   
1  53088835                                        2.8125   
2  52137986                                        3.0000   
3  64072541                                        3.0000   
4  46380687                                        3.0000   

   max_dslam_code_of_dominant_modulation_32days  \
0                                           3.0   
1                                           3.0   
2                                           3.0   
3                                           3.0   
4                                           3.0   

   min_dslam_code_of_dominant_modulation_32days  \
0                                           3.0   
1                                           2.0   
2                                           3.0   
3                                           3.0   
4                                           3.0   

   avg_dslam_avg_bitrate_us_32days  max_dslam_avg_bitrate_us_32days  \
0                      1062.818182                           1094.0   
1                       576.125000                            583.0   
2                       899.303030                            903.0   
3                       895.000000                            895.0   
4                       837.000000                            837.0   

   min_dslam_avg_bitrate_us_32days  avg_dslam_avg_bitrate_ds_32days  \
0                           1025.0                      9003.454545   
1                            537.0                      2122.875000   
2                            899.0                      5182.242424   
3                            895.0                      5159.000000   
4                            837.0                      8111.000000   

   max_dslam_avg_bitrate_ds_32days  min_dslam_avg_bitrate_ds_32days  \
0                           9006.0                           9000.0   
1                           3642.0                            704.0   
2                           5191.0                           4902.0   
3                           5159.0                           5159.0   
4                           8111.0                           8111.0   

   avg_dslam_avg_attenuation_ds_32days  max_dslam_avg_attenuation_ds_32days  \
0                            44.272727                                 45.0   
1                            46.187500                                 48.0   
2                            52.757576                                 57.0   
3                            47.000000                                 47.0   
4                            41.000000                                 41.0   

   min_dslam_avg_attenuation_ds_32days  avg_dslam_avg_attenuation_us_32days  \
0                                 44.0                            23.636364   
1                                 42.0                            34.750000   
2                                 52.0                            28.000000   
3                                 47.0                            24.000000   
4                                 41.0                            20.500000   

   max_dslam_avg_attenuation_us_32days  min_dslam_avg_attenuation_us_32days  \
0                                 24.0                                 23.0   
1                                 35.0                                 33.0   
2                                 28.0                                 28.0   
3                                 24.0                                 24.0   
4                                 21.0                                 20.0   

   avg_dslam_avg_power_us_32days  max_dslam_avg_power_us_32days  \
0                      13.000000                           13.0   
1                      12.687500                           13.0   
2                      12.969697                           13.0   
3                       5.687500                 

## 2. Checks

Check null counts

In [30]:
def null_df(df):
    df1 = pd.DataFrame((df.isnull().sum().sort_values(ascending=False)/df.shape[0])*100,columns=['null_percent'])
    df1.reset_index(inplace=True)
    return df1

In [177]:
null_df_1 = null_df(df_comb_hu_3_s1)

In [31]:
null_df_hnu = null_df(df_comb_hnu_s)
null_df_hnu_3 = null_df(df_comb_hnu_3_s)
null_df_hu = null_df(df_comb_hu_s)
null_df_hu_3 = null_df(df_comb_hu_3_s)

In [48]:
# total_null_cols = list(null_df.loc[null_df.null_percent==100]['index'])
# print(len(total_null_cols))
# total_null_cols

In [32]:
def get_null_cols(df):
    null_cols = list(df.loc[df.null_percent>50]['index'])
    print(len(null_cols))
    return null_cols

In [178]:
null_df_hnu_cols1 = get_null_cols(null_df_1)

49


In [33]:
null_df_hnu_cols = get_null_cols(null_df_hnu)
null_df_hnu_3_cols = get_null_cols(null_df_hnu_3)
null_df_hu_cols = get_null_cols(null_df_hu)
null_df_hu_3_cols = get_null_cols(null_df_hu_3)

49
49
49
49


In [34]:
# null_cols = list(null_df.loc[null_df.null_percent>50]['index'])
# print(len(null_cols))
# null_cols

In [41]:
# #From Ketan Lists
# cols_to_drop = list(df_comb.filter(regex=("natCurrent|natMax|lossOfPower|usedMemoryKb|totalMemoryKb|servis_xdsl|servis_polday")).columns)
# print(len(cols_to_drop))
# cols_to_drop

In [42]:
# total_cols= list(set(null_cols) | set(cols_to_drop))
# print(len(total_cols))

In [38]:
def drop_nulls(df,cols):
    df1 = df.drop(cols,axis=1)
    print('Shape of resulting dataset after dropping null columns:',df1.shape)
    return df1

In [179]:
df_comb_hu_3_n1 = drop_nulls(df_comb_hu_3_s1,null_df_hnu_cols1)

Shape of resulting dataset after dropping null columns: (22174, 644)


In [39]:
#Drop Null columns`
df_comb_hnu_n = drop_nulls(df_comb_hnu_s,null_df_hnu_cols)
df_comb_hnu_3_n = drop_nulls(df_comb_hnu_3_s,null_df_hnu_3_cols)
df_comb_hu_n = drop_nulls(df_comb_hu,null_df_hu_cols)
df_comb_hu_3_n = drop_nulls(df_comb_hu_3_s,null_df_hu_3_cols)

Shape of resulting dataset after dropping null columns: (31637, 636)
Shape of resulting dataset after dropping null columns: (22174, 636)
Shape of resulting dataset after dropping null columns: (26239, 633)
Shape of resulting dataset after dropping null columns: (22174, 636)


In [180]:
df_comb_hu_3_n1.level.value_counts()

0    14961
3     7213
Name: level, dtype: int64

In [40]:
# #Drop Null columns as well as Ketan's list
# df_comb_hnu_nk = drop_nulls(df_comb_hnu,total_cols)
# df_comb_hnu_3_nk = drop_nulls(df_comb_hnu_3,total_cols)
# df_comb_hu_nk = drop_nulls(df_comb_hu_s,total_cols)
# df_comb_hu_3_nk = drop_nulls(df_comb_hu_3,total_cols)

### 2.1 Fill null values

Filling Null values with -1

In [46]:
df_comb_hnu_nf = df_comb_hnu_n.apply(lambda x:x.fillna(-1))
df_comb_hnu_3_nf = df_comb_hnu_3_n.apply(lambda x:x.fillna(-1))
df_comb_hu_nf = df_comb_hu_n.apply(lambda x:x.fillna(-1))
df_comb_hu_3_nf = df_comb_hu_3_n.apply(lambda x:x.fillna(-1))

In [181]:
df_comb_hu_3_nf1 = df_comb_hu_3_n1.apply(lambda x:x.fillna(-1))

In [182]:
df_comb_hu_3_nf1.isnull().values.any()

False

In [48]:
df_comb_hnu_nf.to_csv(path+'/ha35/healthy_nondsl_unhealthy.csv',index=False)
df_comb_hnu_3_nf.to_csv(path+'/ha35/healthy_nondsl_unhealthy_l3.csv',index=False)
df_comb_hu_nf.to_csv(path+'/ha35/healthy_unhealthy.csv',index=False)
df_comb_hu_3_nf.to_csv(path+'/ha35/healthy_unhealthy_l3.csv',index=False)

In [49]:
df_comb_hu_3_nf.level.value_counts()/df_comb_hu_3_nf.shape[0]

0    0.674709
3    0.325291
Name: level, dtype: float64

In [184]:
df_comb_hu_3_nf1.loc[df_comb_hu_3_nf1.level==3]['dslam_platforma_HUAWEI SMARTAX'].value_counts()

1    4836
0    2377
Name: dslam_platforma_HUAWEI SMARTAX, dtype: int64

In [70]:
df_comb_hu_3_nf.level.value_counts()

0    14961
3     7213
Name: level, dtype: int64

Balancing the dataset

In [51]:
train_samples = 7213
test_samples = 7213

In [80]:
df_comb_hu_3_nf.drop('Internet_Pack',axis=1,inplace=True)

In [81]:
df_comb_hu_3_n1_1 = df_comb_hu_3_nf[df_comb_hu_3_nf['level'] == 3][:7213]
df_comb_hu_3_n1_0 = df_comb_hu_3_nf[df_comb_hu_3_nf['level'] == 0][:7213]

In [82]:
df_comb_hu_3_n2 = pd.concat([df_comb_hu_3_n1_1,df_comb_hu_3_n1_0])
df_comb_hu_3_n2 = df_comb_hu_3_n2.sample(frac=1)
df_comb_hu_3_n2 = df_comb_hu_3_n2.reset_index()
df_comb_hu_3_n2.drop('index',axis=1,inplace=True)

In [73]:
df_comb_hu_3_n2.level.value_counts()

0    7213
3    7213
Name: level, dtype: int64

In [121]:
# def correlation(df,threshold):

#     # Create correlation matrix
#     corr_matrix = df.corr().abs()

#     # Select upper triangle of correlation matrix
#     upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(np.bool))

#     # Find features with correlation greater than threshold
#     to_drop = [column for column in upper.columns if any(upper[column] > threshold)]
#     print("Number of columns to drop : ",len(to_drop))
#     print("Proportions of columns to drop : ",round(len(to_drop)/len(df.columns)*100,2),"%")
#     # Drop features 
#     df1 = df.drop(to_drop, axis=1)
    
#     return df1

In [122]:
# df_comb_new2 = correlation(df_comb_new1,0.90)
# print(df_comb_new2.shape)

## 3. Modeling

In [207]:
from sklearn.model_selection import train_test_split


#Import sklearn metrics
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import roc_auc_score
from sklearn.metrics import roc_curve
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import auc

#Import Model libraries
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
import lightgbm as lgb

### 3.1 Split the dataset in Train & Test

In [53]:
def split_train_test(df):
    X = df.drop(['assetid','level'],axis=1)
    y = df['level']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, stratify= y,random_state=100)
    return X_train, X_test, y_train, y_test

In [83]:
X_train, X_test, y_train, y_test = split_train_test(df_comb_hu_3_nf)

In [84]:
X_train2, X_test2, y_train2, y_test2 = split_train_test(df_comb_hu_3_n2) 

In [185]:
X_train3, X_test3, y_train3, y_test3 = split_train_test(df_comb_hu_3_nf1) 

In [213]:
df_comb_hu_3_n2.level.value_counts()

0    14961
3     7213
Name: level, dtype: int64

In [186]:
X_train1, X_test1, y_train1, y_test1 = split_train_test(df_comb_hnu_3_n1)

>1. Since we have different features having different ranges. So features with higher values can impact the model and features with lower values remains insignificant.
>2. Hence Scaling is required

### 3.2 Scaling

In [208]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train3)
X_test_scaled = sc.transform(X_test3)

### 3.3 Prediction Results

In [57]:
def Performance_measure(model,df,actual):
    y_pred=model.predict(df)
    y_prob=model.predict_proba(df)[:,1]
    
    
    print("\nProportion of Positive class predicted :", sum(y_pred)/len(y_pred))
    
    print("\nConfusion Matrix : \n", confusion_matrix(actual,y_pred))
    
    print("\n% Confusion Matrix : \n", confusion_matrix(actual,y_pred)/len(actual))
    
    print("\nClassification Report : \n", classification_report(actual,y_pred))
    
#     print("\nPrecision Score : ", precision_score(actual, y_pred))
#     print("\nRecall Score : ", recall_score(actual, y_pred))
#     print("\nF1 Score : ", f1_score(actual, y_pred))
    
    print("ROC Curve")
    roc_auc = roc_auc_score(actual, y_pred)
    print("\n ROC_AUC : \n", roc_auc)
#     fpr, tpr, thresholds = roc_curve(actual, y_prob)
#     print("AUC Value is : ",auc(fpr, tpr))
#     auc1=auc(fpr,tpr)
#     plt.figure()
#     #plt.plot(fpr, tpr, label='Area Under the curve (area = %0.2f)' % roc_auc)
#     plt.plot(fpr, tpr, label='Area Under the curve (area = %0.2f)' % auc1)
    
    
    
#     plt.plot([0, 1], [0, 1],'r--')
#     plt.xlim([0.0, 1.0])
#     plt.ylim([0.0, 1.05])
#     plt.xlabel('False Positive Rate')
#     plt.ylabel('True Positive Rate')
#     plt.title('Receiver operating characteristic')
#     plt.legend(loc="lower right")
#     #plt.savefig('Log_ROC')
#      plt.show()
    

### Logistic Regression

In [213]:
lr = LogisticRegression(random_state = 21)
lr.fit(X_train_scaled, y_train)

LogisticRegression(random_state=21)

In [214]:
Performance_measure(lr,X_train_scaled,y_train)


Proportion of Positive class predicted : 0.607486470234516

Confusion Matrix : 
 [[12231  1233]
 [ 3684  2808]]

% Confusion Matrix : 
 [[0.61289838 0.06178593]
 [0.18460613 0.14070956]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.77      0.91      0.83     13464
           3       0.69      0.43      0.53      6492

    accuracy                           0.75     19956
   macro avg       0.73      0.67      0.68     19956
weighted avg       0.74      0.75      0.74     19956

ROC Curve

 ROC_AUC : 
 0.6704774036988346


In [215]:
Performance_measure(lr,X_test_scaled,y_test)


Proportion of Positive class predicted : 0.5924256086564472

Confusion Matrix : 
 [[1358  139]
 [ 422  299]]

% Confusion Matrix : 
 [[0.6122633  0.06266907]
 [0.1902615  0.13480613]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.76      0.91      0.83      1497
           3       0.68      0.41      0.52       721

    accuracy                           0.75      2218
   macro avg       0.72      0.66      0.67      2218
weighted avg       0.74      0.75      0.73      2218

ROC Curve

 ROC_AUC : 
 0.660924715820916


### RF model for only healthy & level 3  

In [58]:
rf_model = RandomForestClassifier(n_estimators=600,max_depth=20, 
                               bootstrap = True,
                               criterion = 'gini',
                               max_features = 'sqrt', random_state=100)
# Fit on training data
rf_model.fit(X_train, y_train)

RandomForestClassifier(max_depth=20, max_features='sqrt', n_estimators=600,
                       random_state=100)

In [188]:
#adding noise
rf_model.fit(X_train1, y_train1)

RandomForestClassifier(max_depth=20, max_features='sqrt', n_estimators=200,
                       random_state=100)

In [59]:
print("\nTraining data Performance Measure :")
Performance_measure(rf_model,X_train,y_train)


Training data Performance Measure :

Proportion of Positive class predicted : 0.8543295249549008

Confusion Matrix : 
 [[13464     0]
 [  809  5683]]

% Confusion Matrix : 
 [[0.67468431 0.        ]
 [0.04053919 0.28477651]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.94      1.00      0.97     13464
           3       1.00      0.88      0.93      6492

    accuracy                           0.96     19956
   macro avg       0.97      0.94      0.95     19956
weighted avg       0.96      0.96      0.96     19956

ROC Curve

 ROC_AUC : 
 0.9376925446703634


In [60]:
print("\nTraining data Performance Measure :")
Performance_measure(rf_model,X_test,y_test)


Training data Performance Measure :

Proportion of Positive class predicted : 0.5126239855725879

Confusion Matrix : 
 [[1408   89]
 [ 431  290]]

% Confusion Matrix : 
 [[0.63480613 0.04012624]
 [0.19431921 0.13074842]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.77      0.94      0.84      1497
           3       0.77      0.40      0.53       721

    accuracy                           0.77      2218
   macro avg       0.77      0.67      0.69      2218
weighted avg       0.77      0.77      0.74      2218

ROC Curve

 ROC_AUC : 
 0.6713834511371333


**Insights**
> Adding noise to our model is impacting the performance

In [62]:
var_imp=pd.DataFrame({'columns':X_train.columns, 'Imp':rf_model.feature_importances_})
var_imp.sort_values('Imp',ascending=False)

columns       Imp
128                            avg_dslam_inits_32days  0.008443
286                            avg_dslam_inits_15days  0.007634
615        sum_acs_xdslline_transmitBlocksDelta_1days  0.007490
444                             avg_dslam_inits_7days  0.007234
617         sum_acs_xdslline_receiveBlocksDelta_1days  0.006827
509                         min_dslam_no_counts_1days  0.006382
538                  max_acs_xdslline_cpeUptime_1days  0.006358
127                            sum_dslam_inits_32days  0.006075
535                  max_acs_xdslline_dslUptime_1days  0.006075
632                                      VoIP_enabled  0.006003
616        avg_acs_xdslline_transmitBlocksDelta_1days  0.005723
507                         avg_dslam_no_counts_1days  0.005629
534                  avg_acs_xdslline_dslUptime_1days  0.005529
443                             sum_dslam_inits_7days  0.005434
285                            sum_dslam_inits_15days  0.005126
66         avg_acs_xdslline_cpuUsagePercentage_32days  0.004899
539                  min_acs_xdslline_cpeUptime_1days  0.004851
537                  avg_acs_xdslline_cpeUptime_1days  0.004760
618         avg_acs_xdslline_receiveBlocksDelta_1days  0.004429
457        sum_acs_xdslline_transmitBlocksDelta_7days  0.004351
33                         avg_dslam_no_counts_32days  0.004220
224        avg_acs_xdslline_cpuUsagePercentage_15days  0.003875
191                        avg_dslam_no_counts_15days  0.003733
209                       avg_dslam_sum_ses_us_15days  0.003669
193                        min_dslam_no_counts_15days  0.003642
141       sum_acs_xdslline_transmitBlocksDelta_32days  0.003632
51                        avg_dslam_sum_ses_us_32days  0.003495
223                 min_acs_xdslline_cpeUptime_15days  0.003480
65                  min_acs_xdslline_cpeUptime_32days  0.003402
222                 max_acs_xdslline_cpeUptime_15days  0.003347
142       avg_acs_xdslline_transmitBlocksDelta_32days  0.003285
602                             avg_dslam_inits_1days  0.003276
351                         min_dslam_no_counts_7days  0.003260
221                 avg_acs_xdslline_cpeUptime_15days  0.003246
79                 max_acs_xdslline_initErrors_32days  0.003225
64                  max_acs_xdslline_cpeUptime_32days  0.003214
63                  avg_acs_xdslline_cpeUptime_32days  0.003213
382         avg_acs_xdslline_cpuUsagePercentage_7days  0.003206
218                 avg_acs_xdslline_dslUptime_15days  0.003115
601                             sum_dslam_inits_1days  0.003096
300       avg_acs_xdslline_transmitBlocksDelta_15days  0.003087
67         max_acs_xdslline_cpuUsagePercentage_32days  0.003059
71               min_acs_xdslline_freeMemoryKb_32days  0.002971
381                  min_acs_xdslline_cpeUptime_7days  0.002964
379                  avg_acs_xdslline_cpeUptime_7days  0.002963
299       sum_acs_xdslline_transmitBlocksDelta_15days  0.002962
144        avg_acs_xdslline_receiveBlocksDelta_32days  0.002958
60                  avg_acs_xdslline_dslUptime_32days  0.002955
143        sum_acs_xdslline_receiveBlocksDelta_32days  0.002942
76               max_acs_xdslline_usedMemoryKb_32days  0.002942
52                        max_dslam_sum_ses_us_32days  0.002906
380                  max_acs_xdslline_cpeUptime_7days  0.002881
210                       max_dslam_sum_ses_us_15days  0.002866
349                         avg_dslam_no_counts_7days  0.002859
61                  max_acs_xdslline_dslUptime_32days  0.002854
225        max_acs_xdslline_cpuUsagePercentage_15days  0.002798
376                  avg_acs_xdslline_dslUptime_7days  0.002752
122                     avg_dslam_count_ses_us_32days  0.002739
459         sum_acs_xdslline_receiveBlocksDelta_7days  0.002732
229              min_acs_xdslline_freeMemoryKb_15days  0.002711
70               max_acs_xdslline_freeMemoryKb_32days  0.002693
458        avg_acs_xdslline_transmitBlocksDelta_7days  0.002692
536           

### XGB model for only healthy & level 3  

In [ ]:
n_estimators=50,
                         max_depth=7,
                         min_child_weight=350,#350#250-best
                         oob_score=True,
                         eval_metric='auc',
                         subsample=0.47,#0.55,0.5,.45,0.46
                        colsample_bynode=0.13,#0.17,0.2,0.13-best,0.3-bessst
                         #verbosity=2,
                        objective="binary:logistic", 
                         scale_pos_weight=8,#8,10--0.774
                        eta=0.0001

In [205]:
# Xgboost parameters
xgb_params = {#'learning_rate': 0.01, 
              'max_depth': 7,
              'n_estimators':200,
              'subsample': 0.9,        
              'colsample_bytree': 0.9,
              'objective': 'binary:logistic',
              'silent': 0,  
              'gamma':1,         
              'min_child_weight':100,
              'scale_pos_weight':0.8,
              'eta':0.01,
              'eval_metric':'error',
              'lambda':1,
              'alpha':0} 

In [206]:
clf = xgb.XGBClassifier(**xgb_params, seed = 10)
clf.fit(X_train, y_train)

[11:43:35] WARNING: /opt/concourse/worker/volumes/live/7a2b9f41-3287-451b-6691-43e9a6c0910f/volume/xgboost-split_1619728204606/work/src/learner.cc:541: 
Parameters: { silent } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.




XGBClassifier(alpha=0, base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.9, eta=0.01,
              eval_metric='error', gamma=1, gpu_id=-1, importance_type='gain',
              interaction_constraints='', lambda=1, learning_rate=0.00999999978,
              max_delta_step=0, max_depth=7, min_child_weight=100, missing=nan,
              monotone_constraints='()', n_estimators=200, n_jobs=12,
              num_parallel_tree=1, random_state=10, reg_alpha=0, reg_lambda=1,
              scale_pos_weight=0.8, seed=10, silent=0, subsample=0.9,
              tree_method='exact', ...)

In [207]:
print("\nTraining data Performance Measure :")
Performance_measure(clf,X_train,y_train)


Training data Performance Measure :

Proportion of Positive class predicted : 0.4126500930153898

Confusion Matrix : 
 [[11407   562]
 [ 3892  1878]]

% Confusion Matrix : 
 [[0.64304639 0.03168161]
 [0.21940357 0.10586843]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.75      0.95      0.84     11969
           3       0.77      0.33      0.46      5770

    accuracy                           0.75     17739
   macro avg       0.76      0.64      0.65     17739
weighted avg       0.75      0.75      0.71     17739

ROC Curve

 ROC_AUC : 
 0.6392609851590902


In [208]:
print("\nTraining data Performance Measure :")
Performance_measure(clf,X_test,y_test)


Training data Performance Measure :

Proportion of Positive class predicted : 0.40653889515219843

Confusion Matrix : 
 [[2830  162]
 [1004  439]]

% Confusion Matrix : 
 [[0.63810598 0.03652762]
 [0.22638106 0.09898534]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.74      0.95      0.83      2992
           3       0.73      0.30      0.43      1443

    accuracy                           0.74      4435
   macro avg       0.73      0.63      0.63      4435
weighted avg       0.74      0.74      0.70      4435

ROC Curve

 ROC_AUC : 
 0.625041459600283


#### XGBoost model without much tuing

In [191]:
clf_xgb = xgb.XGBClassifier(n_estimators=200,learning_rate=0.001,max_depth=10,objective = 'binary:logistic',eval_metric='error')
clf_xgb.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, eval_metric='error',
              gamma=0, gpu_id=-1, importance_type='gain',
              interaction_constraints='', learning_rate=0.001, max_delta_step=0,
              max_depth=10, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=200, n_jobs=12,
              num_parallel_tree=1, random_state=0, reg_alpha=0, reg_lambda=1,
              scale_pos_weight=1, subsample=1, tree_method='exact',
              validate_parameters=1, verbosity=None)

In [193]:
print("\nTraining data Performance Measure :")
Performance_measure(clf_xgb,X_train,y_train)


Training data Performance Measure :

Proportion of Positive class predicted : 0.600033823778116

Confusion Matrix : 
 [[11738   231]
 [ 2453  3317]]

% Confusion Matrix : 
 [[0.66170585 0.01302215]
 [0.13828288 0.18698912]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.83      0.98      0.90     11969
           3       0.93      0.57      0.71      5770

    accuracy                           0.85     17739
   macro avg       0.88      0.78      0.80     17739
weighted avg       0.86      0.85      0.84     17739

ROC Curve

 ROC_AUC : 
 0.7777850796823048


In [194]:
print("\nTraining data Performance Measure :")
Performance_measure(clf_xgb,X_test,y_test)


Training data Performance Measure :

Proportion of Positive class predicted : 0.570913190529876

Confusion Matrix : 
 [[2709  283]
 [ 882  561]]

% Confusion Matrix : 
 [[0.610823  0.0638106]
 [0.1988726 0.1264938]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.75      0.91      0.82      2992
           3       0.66      0.39      0.49      1443

    accuracy                           0.74      4435
   macro avg       0.71      0.65      0.66      4435
weighted avg       0.73      0.74      0.71      4435

ROC Curve

 ROC_AUC : 
 0.6470939136380314


##### After adding iptv , voip and Internet pack

In [63]:
clf_xgb = xgb.XGBClassifier(n_estimators=200,learning_rate=0.001,max_depth=7,objective = 'binary:logistic',eval_metric='error')
clf_xgb.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, eval_metric='error',
              gamma=0, gpu_id=-1, importance_type='gain',
              interaction_constraints='', learning_rate=0.001, max_delta_step=0,
              max_depth=7, min_child_weight=1, missing=nan,
              monotone_constraints='()', n_estimators=200, n_jobs=12,
              num_parallel_tree=1, random_state=0, reg_alpha=0, reg_lambda=1,
              scale_pos_weight=1, subsample=1, tree_method='exact',
              validate_parameters=1, verbosity=None)

In [64]:
print("\nTraining data Performance Measure :")
Performance_measure(clf_xgb,X_train,y_train)


Training data Performance Measure :

Proportion of Positive class predicted : 0.5350270595309682

Confusion Matrix : 
 [[12741   723]
 [ 3656  2836]]

% Confusion Matrix : 
 [[0.6384546  0.03622971]
 [0.18320305 0.14211265]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.78      0.95      0.85     13464
           3       0.80      0.44      0.56      6492

    accuracy                           0.78     19956
   macro avg       0.79      0.69      0.71     19956
weighted avg       0.78      0.78      0.76     19956

ROC Curve

 ROC_AUC : 
 0.6915732979463


In [65]:
print("\nTraining data Performance Measure :")
Performance_measure(clf_xgb,X_test,y_test)


Training data Performance Measure :

Proportion of Positive class predicted : 0.5072137060414789

Confusion Matrix : 
 [[1400   97]
 [ 443  278]]

% Confusion Matrix : 
 [[0.63119928 0.04373309]
 [0.19972949 0.12533814]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.76      0.94      0.84      1497
           3       0.74      0.39      0.51       721

    accuracy                           0.76      2218
   macro avg       0.75      0.66      0.67      2218
weighted avg       0.75      0.76      0.73      2218

ROC Curve

 ROC_AUC : 
 0.660389665137024


## Light GBM model oly on healthy & level 3 issue

In [ ]:
boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.094, max_depth=-1, 
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, objective='binary',
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample_for_bin=200000, subsample_freq=0, 
               metric='auc',num_leaves=12,feature_fraction=0.1,subsample=0.75

In [200]:
clf_lgb = lgb.LGBMClassifier(learning_rate=0.094,objective='binary',max_depth=5,num_leaves=50,reg_alpha=0.05,random_state=2)
clf_lgb.fit(X_train, y_train)

LGBMClassifier(learning_rate=0.094, max_depth=5, num_leaves=50,
               objective='binary', random_state=2, reg_alpha=0.05)

In [217]:
clf_lgb2 = lgb.LGBMClassifier(learning_rate=0.094,objective='binary',max_depth=5,num_leaves=50,reg_alpha=0.05,random_state=2)
clf_lgb2.fit(X_train2, y_train2)

LGBMClassifier(learning_rate=0.094, max_depth=5, num_leaves=50,
               objective='binary', random_state=2, reg_alpha=0.05)

In [ ]:
clf_lgb = lgb.LGBMClassifier()
clf_lgb.fit(X_train, y_train)

### Balanced Class

In [218]:
print("\nTraining data Performance Measure :")
Performance_measure(clf_lgb2,X_train2,y_train2)


Training data Performance Measure :

Proportion of Positive class predicted : 1.3744126935222984

Confusion Matrix : 
 [[5586  905]
 [1449 5043]]

% Confusion Matrix : 
 [[0.43025495 0.06970654]
 [0.11160749 0.38843103]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.79      0.86      0.83      6491
           3       0.85      0.78      0.81      6492

    accuracy                           0.82     12983
   macro avg       0.82      0.82      0.82     12983
weighted avg       0.82      0.82      0.82     12983

ROC Curve

 ROC_AUC : 
 0.8186892002605057


In [219]:
print("\nTraining data Performance Measure :")
Performance_measure(clf_lgb2,X_test2,y_test2)


Training data Performance Measure :

Proportion of Positive class predicted : 1.4095634095634095

Confusion Matrix : 
 [[534 188]
 [231 490]]

% Confusion Matrix : 
 [[0.37006237 0.13028413]
 [0.16008316 0.33957034]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.70      0.74      0.72       722
           3       0.72      0.68      0.70       721

    accuracy                           0.71      1443
   macro avg       0.71      0.71      0.71      1443
weighted avg       0.71      0.71      0.71      1443

ROC Curve

 ROC_AUC : 
 0.709611919425544


### Bit Hyperparameter tuning with unbalanced class

In [203]:
print("\nTraining data Performance Measure :")
Performance_measure(clf_lgb,X_train,y_train)


Training data Performance Measure :

Proportion of Positive class predicted : 0.6216810417723659

Confusion Matrix : 
 [[11463   506]
 [ 2600  3170]]

% Confusion Matrix : 
 [[0.64620328 0.02852472]
 [0.14656971 0.17870229]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.82      0.96      0.88     11969
           3       0.86      0.55      0.67      5770

    accuracy                           0.82     17739
   macro avg       0.84      0.75      0.78     17739
weighted avg       0.83      0.82      0.81     17739

ROC Curve

 ROC_AUC : 
 0.753558767428219


In [204]:
print("\nTraining data Performance Measure :")
Performance_measure(clf_lgb,X_test,y_test)


Training data Performance Measure :

Proportion of Positive class predicted : 0.6040586245772266

Confusion Matrix : 
 [[2710  282]
 [ 832  611]]

% Confusion Matrix : 
 [[0.61104848 0.06358512]
 [0.18759865 0.13776776]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.77      0.91      0.83      2992
           3       0.68      0.42      0.52      1443

    accuracy                           0.75      4435
   macro avg       0.72      0.66      0.68      4435
weighted avg       0.74      0.75      0.73      4435

ROC Curve

 ROC_AUC : 
 0.6645860432625139


In [216]:
var_imp=pd.DataFrame({'columns':X_train.columns, 'Imp':clf_lgb.feature_importances_})
var_imp.sort_values('Imp',ascending=False)

columns  Imp
33                         avg_dslam_no_counts_32days  391
66         avg_acs_xdslline_cpuUsagePercentage_32days  331
60                  avg_acs_xdslline_dslUptime_32days  327
191                        avg_dslam_no_counts_15days  299
64                  max_acs_xdslline_cpeUptime_32days  275
141       sum_acs_xdslline_transmitBlocksDelta_32days  267
615        sum_acs_xdslline_transmitBlocksDelta_1days  257
218                 avg_acs_xdslline_dslUptime_15days  256
376                  avg_acs_xdslline_dslUptime_7days  249
632                                      VoIP_enabled  247
67         max_acs_xdslline_cpuUsagePercentage_32days  238
535                  max_acs_xdslline_dslUptime_1days  238
65                  min_acs_xdslline_cpeUptime_32days  235
224        avg_acs_xdslline_cpuUsagePercentage_15days  235
377                  max_acs_xdslline_dslUptime_7days  230
382         avg_acs_xdslline_cpuUsagePercentage_7days  223
193                        min_dslam_no_counts_15days  222
220                 min_acs_xdslline_dslUptime_15days  219
534                  avg_acs_xdslline_dslUptime_1days  210
378                  min_acs_xdslline_dslUptime_7days  208
219                 max_acs_xdslline_dslUptime_15days  199
61                  max_acs_xdslline_dslUptime_32days  198
349                         avg_dslam_no_counts_7days  196
536                  min_acs_xdslline_dslUptime_1days  195
142       avg_acs_xdslline_transmitBlocksDelta_32days  188
299       sum_acs_xdslline_transmitBlocksDelta_15days  185
62                  min_acs_xdslline_dslUptime_32days  184
229              min_acs_xdslline_freeMemoryKb_15days  180
509                         min_dslam_no_counts_1days  179
70               max_acs_xdslline_freeMemoryKb_32days  178
541         max_acs_xdslline_cpuUsagePercentage_1days  170
63                  avg_acs_xdslline_cpeUptime_32days  169
143        sum_acs_xdslline_receiveBlocksDelta_32days  165
128                            avg_dslam_inits_32days  162
221                 avg_acs_xdslline_cpeUptime_15days  160
223                 min_acs_xdslline_cpeUptime_15days  158
222                 max_acs_xdslline_cpeUptime_15days  157
351                         min_dslam_no_counts_7days  156
225        max_acs_xdslline_cpuUsagePercentage_15days  156
77               min_acs_xdslline_usedMemoryKb_32days  156
383         max_acs_xdslline_cpuUsagePercentage_7days  155
384         min_acs_xdslline_cpuUsagePercentage_7days  149
79                 max_acs_xdslline_initErrors_32days  148
300       avg_acs_xdslline_transmitBlocksDelta_15days  147
35                         min_dslam_no_counts_32days  147
587                       sum_dslam_count_cv_ds_1days  146
92          min_acs_xdslline_downNoiseMarginDb_32days  145
457        sum_acs_xdslline_transmitBlocksDelta_7days  143
91          max_acs_xdslline_downNoiseMarginDb_32days  143
144        avg_acs_xdslline_receiveBlocksDelta_32days  139
386               max_acs_xdslline_freeMemoryKb_7days  138
40                         max_dslam_sum_cv_ds_32days  138
71               min_acs_xdslline_freeMemoryKb_32days  138
106           max_acs_xdslline_upNoiseMarginDb_32days  135
76               max_acs_xdslline_usedMemoryKb_32days  134
228              max_acs_xdslline_freeMemoryKb_15days  131
458        avg_acs_xdslline_transmitBlocksDelta_7days  130
381                  min_acs_xdslline_cpeUptime_7days  129
301        sum_acs_xdslline_receiveBlocksDelta_15days  127
286                            avg_dslam_inits_15days  124
112                      avg_dslam_count_cv_us_32days  124
72              avg_acs_xdslline_totalMemoryKb_32days  124
234              max_acs_xdslline_usedMemoryKb_15days  124
616        avg_acs_xdslline_transmitBlocksDelta_1days  122
78                 avg_acs_xdslline_initErrors_32days  122
380                  max_acs_xdslline_cpeUptime_7days  122
393               min_acs_xdslline_usedMemoryKb_7days  118
148              avg_acs_xdslline_

#### After adding IPTV, VoIP and Internet Pack

In [107]:
clf_lgb = lgb.LGBMClassifier(n_estimators=800,learning_rate=0.04,objective='binary',max_depth=7,num_leaves=50,reg_alpha=0.05,random_state=2)
clf_lgb.fit(X_train, y_train)

LGBMClassifier(learning_rate=0.04, max_depth=7, n_estimators=800, num_leaves=50,
               objective='binary', random_state=2, reg_alpha=0.05)

In [108]:
print("\nTraining data Performance Measure :")
Performance_measure(clf_lgb,X_train,y_train)


Training data Performance Measure :

Proportion of Positive class predicted : 0.9203247143716176

Confusion Matrix : 
 [[13456     8]
 [  378  6114]]

% Confusion Matrix : 
 [[6.74283424e-01 4.00881940e-04]
 [1.89416717e-02 3.06374023e-01]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.97      1.00      0.99     13464
           3       1.00      0.94      0.97      6492

    accuracy                           0.98     19956
   macro avg       0.99      0.97      0.98     19956
weighted avg       0.98      0.98      0.98     19956

ROC Curve

 ROC_AUC : 
 0.9705901573086525


In [109]:
print("\nTraining data Performance Measure :")
Performance_measure(clf_lgb,X_test,y_test)


Training data Performance Measure :

Proportion of Positive class predicted : 0.6357078449053201

Confusion Matrix : 
 [[1372  125]
 [ 376  345]]

% Confusion Matrix : 
 [[0.61857529 0.05635708]
 [0.16952209 0.15554554]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.78      0.92      0.85      1497
           3       0.73      0.48      0.58       721

    accuracy                           0.77      2218
   macro avg       0.76      0.70      0.71      2218
weighted avg       0.77      0.77      0.76      2218

ROC Curve

 ROC_AUC : 
 0.697500873221246


In [217]:
var_imp=pd.DataFrame({'columns':X_train.columns, 'Imp':clf_lgb.feature_importances_})
var_imp.sort_values('Imp',ascending=False)

columns  Imp
33                         avg_dslam_no_counts_32days  391
66         avg_acs_xdslline_cpuUsagePercentage_32days  331
60                  avg_acs_xdslline_dslUptime_32days  327
191                        avg_dslam_no_counts_15days  299
64                  max_acs_xdslline_cpeUptime_32days  275
141       sum_acs_xdslline_transmitBlocksDelta_32days  267
615        sum_acs_xdslline_transmitBlocksDelta_1days  257
218                 avg_acs_xdslline_dslUptime_15days  256
376                  avg_acs_xdslline_dslUptime_7days  249
632                                      VoIP_enabled  247
67         max_acs_xdslline_cpuUsagePercentage_32days  238
535                  max_acs_xdslline_dslUptime_1days  238
65                  min_acs_xdslline_cpeUptime_32days  235
224        avg_acs_xdslline_cpuUsagePercentage_15days  235
377                  max_acs_xdslline_dslUptime_7days  230
382         avg_acs_xdslline_cpuUsagePercentage_7days  223
193                        min_dslam_no_counts_15days  222
220                 min_acs_xdslline_dslUptime_15days  219
534                  avg_acs_xdslline_dslUptime_1days  210
378                  min_acs_xdslline_dslUptime_7days  208
219                 max_acs_xdslline_dslUptime_15days  199
61                  max_acs_xdslline_dslUptime_32days  198
349                         avg_dslam_no_counts_7days  196
536                  min_acs_xdslline_dslUptime_1days  195
142       avg_acs_xdslline_transmitBlocksDelta_32days  188
299       sum_acs_xdslline_transmitBlocksDelta_15days  185
62                  min_acs_xdslline_dslUptime_32days  184
229              min_acs_xdslline_freeMemoryKb_15days  180
509                         min_dslam_no_counts_1days  179
70               max_acs_xdslline_freeMemoryKb_32days  178
541         max_acs_xdslline_cpuUsagePercentage_1days  170
63                  avg_acs_xdslline_cpeUptime_32days  169
143        sum_acs_xdslline_receiveBlocksDelta_32days  165
128                            avg_dslam_inits_32days  162
221                 avg_acs_xdslline_cpeUptime_15days  160
223                 min_acs_xdslline_cpeUptime_15days  158
222                 max_acs_xdslline_cpeUptime_15days  157
351                         min_dslam_no_counts_7days  156
225        max_acs_xdslline_cpuUsagePercentage_15days  156
77               min_acs_xdslline_usedMemoryKb_32days  156
383         max_acs_xdslline_cpuUsagePercentage_7days  155
384         min_acs_xdslline_cpuUsagePercentage_7days  149
79                 max_acs_xdslline_initErrors_32days  148
300       avg_acs_xdslline_transmitBlocksDelta_15days  147
35                         min_dslam_no_counts_32days  147
587                       sum_dslam_count_cv_ds_1days  146
92          min_acs_xdslline_downNoiseMarginDb_32days  145
457        sum_acs_xdslline_transmitBlocksDelta_7days  143
91          max_acs_xdslline_downNoiseMarginDb_32days  143
144        avg_acs_xdslline_receiveBlocksDelta_32days  139
386               max_acs_xdslline_freeMemoryKb_7days  138
40                         max_dslam_sum_cv_ds_32days  138
71               min_acs_xdslline_freeMemoryKb_32days  138
106           max_acs_xdslline_upNoiseMarginDb_32days  135
76               max_acs_xdslline_usedMemoryKb_32days  134
228              max_acs_xdslline_freeMemoryKb_15days  131
458        avg_acs_xdslline_transmitBlocksDelta_7days  130
381                  min_acs_xdslline_cpeUptime_7days  129
301        sum_acs_xdslline_receiveBlocksDelta_15days  127
286                            avg_dslam_inits_15days  124
112                      avg_dslam_count_cv_us_32days  124
72              avg_acs_xdslline_totalMemoryKb_32days  124
234              max_acs_xdslline_usedMemoryKb_15days  124
616        avg_acs_xdslline_transmitBlocksDelta_1days  122
78                 avg_acs_xdslline_initErrors_32days  122
380                  max_acs_xdslline_cpeUptime_7days  122
393               min_acs_xdslline_usedMemoryKb_7days  118
148              avg_acs_xdslline_

#### BAlanced Class

In [110]:
clf_lgb1 = lgb.LGBMClassifier(n_estimators=250,learning_rate=0.01,objective='binary',max_depth=7,num_leaves=50,reg_alpha=0.05,random_state=2)
clf_lgb1.fit(X_train2, y_train2)

LGBMClassifier(learning_rate=0.01, max_depth=7, n_estimators=250, num_leaves=50,
               objective='binary', random_state=2, reg_alpha=0.05)

In [111]:
print("\nTraining data Performance Measure :")
Performance_measure(clf_lgb1,X_train2,y_train2)


Training data Performance Measure :

Proportion of Positive class predicted : 1.3792651929446198

Confusion Matrix : 
 [[5410 1081]
 [1604 4888]]

% Confusion Matrix : 
 [[0.41669876 0.08326273]
 [0.12354618 0.37649234]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.77      0.83      0.80      6491
           3       0.82      0.75      0.78      6492

    accuracy                           0.79     12983
   macro avg       0.80      0.79      0.79     12983
weighted avg       0.80      0.79      0.79     12983

ROC Curve

 ROC_AUC : 
 0.7931941976059937


In [112]:
print("\nTraining data Performance Measure :")
Performance_measure(clf_lgb1,X_test2,y_test2)


Training data Performance Measure :

Proportion of Positive class predicted : 1.3305613305613306

Confusion Matrix : 
 [[549 173]
 [254 467]]

% Confusion Matrix : 
 [[0.38045738 0.11988912]
 [0.17602218 0.32363132]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.68      0.76      0.72       722
           3       0.73      0.65      0.69       721

    accuracy                           0.70      1443
   macro avg       0.71      0.70      0.70      1443
weighted avg       0.71      0.70      0.70      1443

ROC Curve

 ROC_AUC : 
 0.7040496617117654


In [100]:
var_imp=pd.DataFrame({'columns':X_train2.columns, 'Imp':clf_lgb1.feature_importances_})
var_imp.sort_values('Imp',ascending=False)

columns  Imp
632                                      VoIP_enabled   63
66         avg_acs_xdslline_cpuUsagePercentage_32days   38
193                        min_dslam_no_counts_15days   33
509                         min_dslam_no_counts_1days   28
64                  max_acs_xdslline_cpeUptime_32days   26
79                 max_acs_xdslline_initErrors_32days   23
224        avg_acs_xdslline_cpuUsagePercentage_15days   22
615        sum_acs_xdslline_transmitBlocksDelta_1days   22
444                             avg_dslam_inits_7days   22
33                         avg_dslam_no_counts_32days   21
141       sum_acs_xdslline_transmitBlocksDelta_32days   21
631                                      IPTV_enabled   21
67         max_acs_xdslline_cpuUsagePercentage_32days   20
535                  max_acs_xdslline_dslUptime_1days   20
70               max_acs_xdslline_freeMemoryKb_32days   20
61                  max_acs_xdslline_dslUptime_32days   19
128                            avg_dslam_inits_32days   19
112                      avg_dslam_count_cv_us_32days   19
65                  min_acs_xdslline_cpeUptime_32days   16
72              avg_acs_xdslline_totalMemoryKb_32days   16
250         min_acs_xdslline_downNoiseMarginDb_15days   16
60                  avg_acs_xdslline_dslUptime_32days   15
617         sum_acs_xdslline_receiveBlocksDelta_1days   15
382         avg_acs_xdslline_cpuUsagePercentage_7days   15
142       avg_acs_xdslline_transmitBlocksDelta_32days   14
223                 min_acs_xdslline_cpeUptime_15days   14
71               min_acs_xdslline_freeMemoryKb_32days   14
378                  min_acs_xdslline_dslUptime_7days   14
191                        avg_dslam_no_counts_15days   14
541         max_acs_xdslline_cpuUsagePercentage_1days   14
221                 avg_acs_xdslline_cpeUptime_15days   13
68         min_acs_xdslline_cpuUsagePercentage_32days   13
218                 avg_acs_xdslline_dslUptime_15days   13
262             min_acs_xdslline_upMaxRateKbps_15days   12
222                 max_acs_xdslline_cpeUptime_15days   12
271                      sum_dslam_count_cv_ds_15days   12
536                  min_acs_xdslline_dslUptime_1days   12
616        avg_acs_xdslline_transmitBlocksDelta_1days   12
225        max_acs_xdslline_cpuUsagePercentage_15days   12
587                       sum_dslam_count_cv_ds_1days   12
91          max_acs_xdslline_downNoiseMarginDb_32days   12
92          min_acs_xdslline_downNoiseMarginDb_32days   12
209                       avg_dslam_sum_ses_us_15days   12
286                            avg_dslam_inits_15days   12
219                 max_acs_xdslline_dslUptime_15days   11
430                       avg_dslam_count_cv_ds_7days   11
457        sum_acs_xdslline_transmitBlocksDelta_7days   11
539                  min_acs_xdslline_cpeUptime_1days   11
76               max_acs_xdslline_usedMemoryKb_32days   11
534                  avg_acs_xdslline_dslUptime_1days   11
229              min_acs_xdslline_freeMemoryKb_15days   11
351                         min_dslam_no_counts_7days   11
114                      avg_dslam_count_cv_ds_32days   11
152                  avg_acs_xdslline_fecdelta_32days   10
144        avg_acs_xdslline_receiveBlocksDelta_32days   10
143        sum_acs_xdslline_receiveBlocksDelta_32days   10
94               max_acs_xdslline_downPowerDbm_32days   10
129            sum_acs_xdslline_cellDelinDelta_32days   10
62                  min_acs_xdslline_dslUptime_32days   10
376                  avg_acs_xdslline_dslUptime_7days   10
264           max_acs_xdslline_upNoiseMarginDb_15days   10
269                      sum_dslam_count_cv_us_15days   10
602                             avg_dslam_inits_1days   10
220                 min_acs_xdslline_dslUptime_15days   10
302        avg_acs_xdslline_receiveBlocksDelta_15days    9
395                 max_acs_xdslline_initErrors_7days    9
100            max_acs_xdslline_upCurrRateKbps_32days    9
428                       avg_dsla

In [189]:
clf_lgb2 = lgb.LGBMClassifier(n_estimators=200,learning_rate=0.01,objective='binary',max_depth=5,num_leaves=50,reg_alpha=0.05,random_state=2)
clf_lgb2.fit(X_train3, y_train3)

LGBMClassifier(learning_rate=0.01, max_depth=5, n_estimators=200, num_leaves=50,
               objective='binary', random_state=2, reg_alpha=0.05)

In [190]:
print("\nTraining data Performance Measure :")
Performance_measure(clf_lgb2,X_train3,y_train3)


Training data Performance Measure :

Proportion of Positive class predicted : 0.4485868911605532

Confusion Matrix : 
 [[12886   578]
 [ 4086  2406]]

% Confusion Matrix : 
 [[0.64572059 0.02896372]
 [0.20475045 0.12056524]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.76      0.96      0.85     13464
           3       0.81      0.37      0.51      6492

    accuracy                           0.77     19956
   macro avg       0.78      0.66      0.68     19956
weighted avg       0.77      0.77      0.74     19956

ROC Curve

 ROC_AUC : 
 0.6638403442932094


In [191]:
print("\nTraining data Performance Measure :")
Performance_measure(clf_lgb2,X_test3,y_test3)


Training data Performance Measure :

Proportion of Positive class predicted : 0.43958521190261496

Confusion Matrix : 
 [[1431   66]
 [ 462  259]]

% Confusion Matrix : 
 [[0.64517583 0.02975654]
 [0.20829576 0.11677187]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.76      0.96      0.84      1497
           3       0.80      0.36      0.50       721

    accuracy                           0.76      2218
   macro avg       0.78      0.66      0.67      2218
weighted avg       0.77      0.76      0.73      2218

ROC Curve

 ROC_AUC : 
 0.6575675623090842


In [192]:
var_imp=pd.DataFrame({'columns':X_train2.columns, 'Imp':clf_lgb1.feature_importances_})
var_imp.sort_values('Imp',ascending=False)

columns  Imp
632                                      VoIP_enabled  509
66         avg_acs_xdslline_cpuUsagePercentage_32days  262
615        sum_acs_xdslline_transmitBlocksDelta_1days  234
193                        min_dslam_no_counts_15days  218
509                         min_dslam_no_counts_1days  217
444                             avg_dslam_inits_7days  198
631                                      IPTV_enabled  194
79                 max_acs_xdslline_initErrors_32days  181
64                  max_acs_xdslline_cpeUptime_32days  150
128                            avg_dslam_inits_32days  129
224        avg_acs_xdslline_cpuUsagePercentage_15days  128
33                         avg_dslam_no_counts_32days  127
72              avg_acs_xdslline_totalMemoryKb_32days  125
535                  max_acs_xdslline_dslUptime_1days  118
112                      avg_dslam_count_cv_us_32days  117
65                  min_acs_xdslline_cpeUptime_32days  115
237                max_acs_xdslline_initErrors_15days  107
617         sum_acs_xdslline_receiveBlocksDelta_1days   94
223                 min_acs_xdslline_cpeUptime_15days   92
63                  avg_acs_xdslline_cpeUptime_32days   90
222                 max_acs_xdslline_cpeUptime_15days   89
382         avg_acs_xdslline_cpuUsagePercentage_7days   85
70               max_acs_xdslline_freeMemoryKb_32days   82
351                         min_dslam_no_counts_7days   82
379                  avg_acs_xdslline_cpeUptime_7days   82
61                  max_acs_xdslline_dslUptime_32days   81
209                       avg_dslam_sum_ses_us_15days   79
142       avg_acs_xdslline_transmitBlocksDelta_32days   78
219                 max_acs_xdslline_dslUptime_15days   77
106           max_acs_xdslline_upNoiseMarginDb_32days   77
67         max_acs_xdslline_cpuUsagePercentage_32days   73
191                        avg_dslam_no_counts_15days   71
264           max_acs_xdslline_upNoiseMarginDb_15days   70
286                            avg_dslam_inits_15days   70
443                             sum_dslam_inits_7days   70
141       sum_acs_xdslline_transmitBlocksDelta_32days   68
250         min_acs_xdslline_downNoiseMarginDb_15days   67
539                  min_acs_xdslline_cpeUptime_1days   65
534                  avg_acs_xdslline_dslUptime_1days   65
349                         avg_dslam_no_counts_7days   65
60                  avg_acs_xdslline_dslUptime_32days   61
71               min_acs_xdslline_freeMemoryKb_32days   61
602                             avg_dslam_inits_1days   61
601                             sum_dslam_inits_1days   59
377                  max_acs_xdslline_dslUptime_7days   58
143        sum_acs_xdslline_receiveBlocksDelta_32days   58
457        sum_acs_xdslline_transmitBlocksDelta_7days   57
127                            sum_dslam_inits_32days   56
113                      sum_dslam_count_cv_ds_32days   55
616        avg_acs_xdslline_transmitBlocksDelta_1days   54
618         avg_acs_xdslline_receiveBlocksDelta_1days   54
507                         avg_dslam_no_counts_1days   54
62                  min_acs_xdslline_dslUptime_32days   53
100            max_acs_xdslline_upCurrRateKbps_32days   53
272                      avg_dslam_count_cv_ds_15days   51
114                      avg_dslam_count_cv_ds_32days   50
353                         max_dslam_sum_cv_us_7days   50
35                         min_dslam_no_counts_32days   48
181               min_dslam_avg_att_bitrate_us_15days   46
530                        min_dslam_sum_fec_ds_1days   45
372                        min_dslam_sum_fec_ds_7days   44
229              min_acs_xdslline_freeMemoryKb_15days   44
269                      sum_dslam_count_cv_us_15days   43
378                  min_acs_xdslline_dslUptime_7days   43
467                   sum_acs_xdslline_fecdelta_7days   42
536                  min_acs_xdslline_dslUptime_1days   42
537                  avg_acs_xdslline_cpeUptime_1days   42
430                       avg_dsla

#### XGB

In [198]:
print("\nTraining data Performance Measure :")
Performance_measure(clf_xgb,X_test,y_test)


Training data Performance Measure :

Proportion of Positive class predicted : 0.570913190529876

Confusion Matrix : 
 [[2709  283]
 [ 882  561]]

% Confusion Matrix : 
 [[0.610823  0.0638106]
 [0.1988726 0.1264938]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.75      0.91      0.82      2992
           3       0.66      0.39      0.49      1443

    accuracy                           0.74      4435
   macro avg       0.71      0.65      0.66      4435
weighted avg       0.73      0.74      0.71      4435

ROC Curve

 ROC_AUC : 
 0.6470939136380314


In [135]:
print("\nTraining data Performance Measure :")
Performance_measure(clf_xgb,X_test,y_test)


Training data Performance Measure :

Proportion of Positive class predicted : 0.5734896302975654

Confusion Matrix : 
 [[1358  139]
 [ 436  285]]

% Confusion Matrix : 
 [[0.6122633  0.06266907]
 [0.19657349 0.12849414]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.76      0.91      0.83      1497
           3       0.67      0.40      0.50       721

    accuracy                           0.74      2218
   macro avg       0.71      0.65      0.66      2218
weighted avg       0.73      0.74      0.72      2218

ROC Curve

 ROC_AUC : 
 0.6512159779568384


## Light GBM model

In [147]:
print("\nTraining data Performance Measure :")
Performance_measure(clf_lgb,X_train,y_train)


Training data Performance Measure :

Proportion of Positive class predicted : 0.5915514131088394

Confusion Matrix : 
 [[12583   881]
 [ 3438  3054]]

% Confusion Matrix : 
 [[0.63053718 0.04414712]
 [0.17227901 0.15303668]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.79      0.93      0.85     13464
           3       0.78      0.47      0.59      6492

    accuracy                           0.78     19956
   macro avg       0.78      0.70      0.72     19956
weighted avg       0.78      0.78      0.77     19956

ROC Curve

 ROC_AUC : 
 0.702495694687442


In [148]:
print("\nTraining data Performance Measure :")
Performance_measure(clf_lgb,X_test,y_test)


Training data Performance Measure :

Proportion of Positive class predicted : 0.5532010820559062

Confusion Matrix : 
 [[1381  116]
 [ 428  293]]

% Confusion Matrix : 
 [[0.622633   0.05229937]
 [0.19296664 0.13210099]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.76      0.92      0.84      1497
           3       0.72      0.41      0.52       721

    accuracy                           0.75      2218
   macro avg       0.74      0.66      0.68      2218
weighted avg       0.75      0.75      0.73      2218

ROC Curve

 ROC_AUC : 
 0.6644458588930057


## XGBoost with Healthy & Level 3 issue

In [103]:
print("\nTraining data Performance Measure :")
Performance_measure(clf,X_train,y_train)


Training data Performance Measure :

Proportion of Positive class predicted : 0.40018039687312085

Confusion Matrix : 
 [[12854   610]
 [ 4440  2052]]

% Confusion Matrix : 
 [[0.64411706 0.03056725]
 [0.22248948 0.10282622]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.74      0.95      0.84     13464
           3       0.77      0.32      0.45      6492

    accuracy                           0.75     19956
   macro avg       0.76      0.64      0.64     19956
weighted avg       0.75      0.75      0.71     19956

ROC Curve

 ROC_AUC : 
 0.6353876648402037


In [104]:
print("\nTraining data Performance Measure :")
Performance_measure(clf,X_test,y_test)


Training data Performance Measure :

Proportion of Positive class predicted : 0.39224526600541026

Confusion Matrix : 
 [[1419   78]
 [ 509  212]]

% Confusion Matrix : 
 [[0.63976555 0.03516682]
 [0.22948602 0.09558161]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.74      0.95      0.83      1497
           3       0.73      0.29      0.42       721

    accuracy                           0.74      2218
   macro avg       0.73      0.62      0.62      2218
weighted avg       0.73      0.74      0.70      2218

ROC Curve

 ROC_AUC : 
 0.6209659263047592


## On Healthy, NonDSL & Unhealthy data for all levels

In [221]:
# #boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
#                importance_type='split', learning_rate=0.095, max_depth=7, num_leaves = 130,
#                min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
#                n_estimators=100, n_jobs=-1, 

In [174]:
clf_lgb_1 = lgb.LGBMClassifier(objective='binary')
clf_lgb_1.fit(X_train, y_train)

LGBMClassifier()

In [175]:
print("\nTraining data Performance Measure :")
Performance_measure(clf_lgb_1,X_train,y_train)


Training data Performance Measure :

Proportion of Positive class predicted : 0.870277738078224

Confusion Matrix : 
 [[11697     0   272     0]
 [  606   621    88     0]
 [ 1886     0  3884     0]
 [  804     0   238   895]]

% Confusion Matrix : 
 [[0.55723882 0.         0.01295793 0.        ]
 [0.02886952 0.02958411 0.00419227 0.        ]
 [0.08984803 0.         0.18503168 0.        ]
 [0.03830213 0.         0.01133819 0.04263732]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.78      0.98      0.87     11969
           2       1.00      0.47      0.64      1315
           3       0.87      0.67      0.76      5770
           4       1.00      0.46      0.63      1937

    accuracy                           0.81     20991
   macro avg       0.91      0.65      0.72     20991
weighted avg       0.84      0.81      0.80     20991

ROC Curve


ValueError: multi_class must be in ('ovo', 'ovr')

In [176]:
print("\nTraining data Performance Measure :")
Performance_measure(clf_lgb_1,X_test,y_test)


Training data Performance Measure :

Proportion of Positive class predicted : 0.7048399390243902

Confusion Matrix : 
 [[2724    0  262    6]
 [ 237    2   89    1]
 [ 790    2  640   11]
 [ 272    0  202   10]]

% Confusion Matrix : 
 [[5.19054878e-01 0.00000000e+00 4.99237805e-02 1.14329268e-03]
 [4.51600610e-02 3.81097561e-04 1.69588415e-02 1.90548780e-04]
 [1.50533537e-01 3.81097561e-04 1.21951220e-01 2.09603659e-03]
 [5.18292683e-02 0.00000000e+00 3.84908537e-02 1.90548780e-03]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.68      0.91      0.78      2992
           2       0.50      0.01      0.01       329
           3       0.54      0.44      0.49      1443
           4       0.36      0.02      0.04       484

    accuracy                           0.64      5248
   macro avg       0.52      0.35      0.33      5248
weighted avg       0.60      0.64      0.58      5248

ROC Curve


ValueError: multi_class must be in ('ovo', 'ovr')

**Insights**
> For all levels it is difficult for model to predict hence let's focus on 1 class only

### Only on Healthy data & Level 3 Unhealthy data

In [84]:
print("\nTraining data Performance Measure :")
Performance_measure(model,X_train,y_train)


Training data Performance Measure :

Proportion of Positive class predicted : 0.5646422128683103

Confusion Matrix : 
 [[13464     0]
 [  858  5634]]

% Confusion Matrix : 
 [[0.67468431 0.        ]
 [0.04299459 0.28232111]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.94      1.00      0.97     13464
           2       1.00      0.87      0.93      6492

    accuracy                           0.96     19956
   macro avg       0.97      0.93      0.95     19956
weighted avg       0.96      0.96      0.96     19956



In [85]:
print("\nTraining data Performance Measure :")
Performance_measure(model,X_test,y_test)


Training data Performance Measure :

Proportion of Positive class predicted : 0.33994589720468893

Confusion Matrix : 
 [[1383  114]
 [ 458  263]]

% Confusion Matrix : 
 [[0.62353472 0.05139766]
 [0.20649234 0.11857529]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.75      0.92      0.83      1497
           2       0.70      0.36      0.48       721

    accuracy                           0.74      2218
   macro avg       0.72      0.64      0.65      2218
weighted avg       0.73      0.74      0.72      2218



### Only Healthy & Unhealthy data

In [60]:
print("\nTraining data Performance Measure :")
Performance_measure(model,X_train,y_train)


Training data Performance Measure :

Proportion of Positive class predicted : 0.7404615710353589

Confusion Matrix : 
 [[13465     0     0     0]
 [  493   986     0     0]
 [  789     0  5703     0]
 [  481     0     0  1698]]

% Confusion Matrix : 
 [[0.57018844 0.         0.         0.        ]
 [0.02087656 0.04175312 0.         0.        ]
 [0.03341097 0.         0.24149905 0.        ]
 [0.02036841 0.         0.         0.07190345]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.88      1.00      0.94     13465
           1       1.00      0.67      0.80      1479
           2       1.00      0.88      0.94      6492
           3       1.00      0.78      0.88      2179

    accuracy                           0.93     23615
   macro avg       0.97      0.83      0.89     23615
weighted avg       0.93      0.93      0.92     23615



In [61]:
print("\nTraining data Performance Measure :")
Performance_measure(model,X_test,y_test)


Training data Performance Measure :

Proportion of Positive class predicted : 0.390625

Confusion Matrix : 
 [[1384    0  112    0]
 [ 136    0   29    0]
 [ 445    0  275    1]
 [ 147    0   95    0]]

% Confusion Matrix : 
 [[5.27439024e-01 0.00000000e+00 4.26829268e-02 0.00000000e+00]
 [5.18292683e-02 0.00000000e+00 1.10518293e-02 0.00000000e+00]
 [1.69588415e-01 0.00000000e+00 1.04801829e-01 3.81097561e-04]
 [5.60213415e-02 0.00000000e+00 3.62042683e-02 0.00000000e+00]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.66      0.93      0.77      1496
           1       0.00      0.00      0.00       165
           2       0.54      0.38      0.45       721
           3       0.00      0.00      0.00       242

    accuracy                           0.63      2624
   macro avg       0.30      0.33      0.30      2624
weighted avg       0.52      0.63      0.56      2624



### Combined Healthy, Non-DSL & Unhealthy data

In [47]:
print("\nTraining data Performance Measure :")
Performance_measure(model,X_train,y_train)


Training data Performance Measure :

Proportion of Positive class predicted : 0.5178239033470305

Confusion Matrix : 
 [[18323     0     0     0]
 [  781   698     0     0]
 [ 1551     0  4941     0]
 [  791     0     0  1388]]

% Confusion Matrix : 
 [[0.64352193 0.         0.         0.        ]
 [0.02742949 0.02451445 0.         0.        ]
 [0.05447266 0.         0.17353282 0.        ]
 [0.0277807  0.         0.         0.04874794]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.85      1.00      0.92     18323
           1       1.00      0.47      0.64      1479
           2       1.00      0.76      0.86      6492
           3       1.00      0.64      0.78      2179

    accuracy                           0.89     28473
   macro avg       0.96      0.72      0.80     28473
weighted avg       0.91      0.89      0.88     28473



In [48]:
print("\nTesting data Performance Measure :")
Performance_measure(model,X_test,y_test)


Testing data Performance Measure :

Proportion of Positive class predicted : 0.18584070796460178

Confusion Matrix : 
 [[1956    0   80    0]
 [ 154    0   11    0]
 [ 573    0  148    0]
 [ 187    0   55    0]]

% Confusion Matrix : 
 [[0.6182048  0.         0.02528445 0.        ]
 [0.04867257 0.         0.00347661 0.        ]
 [0.18109987 0.         0.04677623 0.        ]
 [0.0591024  0.         0.01738306 0.        ]]

Classification Report : 
               precision    recall  f1-score   support

           0       0.68      0.96      0.80      2036
           1       0.00      0.00      0.00       165
           2       0.50      0.21      0.29       721
           3       0.00      0.00      0.00       242

    accuracy                           0.66      3164
   macro avg       0.30      0.29      0.27      3164
weighted avg       0.55      0.66      0.58      3164



In [143]:
var_imp=pd.DataFrame({'columns':X_train.columns, 'Imp':clf_lgb.feature_importances_})
var_imp.sort_values('Imp',ascending=False)

columns  Imp
66         avg_acs_xdslline_cpuUsagePercentage_32days   54
193                        min_dslam_no_counts_15days   39
141       sum_acs_xdslline_transmitBlocksDelta_32days   39
33                         avg_dslam_no_counts_32days   39
615        sum_acs_xdslline_transmitBlocksDelta_1days   38
100            max_acs_xdslline_upCurrRateKbps_32days   36
79                 max_acs_xdslline_initErrors_32days   31
61                  max_acs_xdslline_dslUptime_32days   28
60                  avg_acs_xdslline_dslUptime_32days   26
509                         min_dslam_no_counts_1days   26
65                  min_acs_xdslline_cpeUptime_32days   24
67         max_acs_xdslline_cpuUsagePercentage_32days   24
128                            avg_dslam_inits_32days   22
535                  max_acs_xdslline_dslUptime_1days   22
191                        avg_dslam_no_counts_15days   19
382         avg_acs_xdslline_cpuUsagePercentage_7days   19
77               min_acs_xdslline_usedMemoryKb_32days   18
112                      avg_dslam_count_cv_us_32days   18
70               max_acs_xdslline_freeMemoryKb_32days   18
536                  min_acs_xdslline_dslUptime_1days   18
270                      avg_dslam_count_cv_us_15days   17
85           max_acs_xdslline_downCurrRateKbps_32days   17
63                  avg_acs_xdslline_cpeUptime_32days   17
237                max_acs_xdslline_initErrors_15days   17
143        sum_acs_xdslline_receiveBlocksDelta_32days   17
224        avg_acs_xdslline_cpuUsagePercentage_15days   17
587                       sum_dslam_count_cv_ds_1days   16
72              avg_acs_xdslline_totalMemoryKb_32days   16
71               min_acs_xdslline_freeMemoryKb_32days   16
4                     max_dslam_avg_bitrate_us_32days   16
377                  max_acs_xdslline_dslUptime_7days   16
64                  max_acs_xdslline_cpeUptime_32days   16
62                  min_acs_xdslline_dslUptime_32days   16
228              max_acs_xdslline_freeMemoryKb_15days   16
142       avg_acs_xdslline_transmitBlocksDelta_32days   15
107           min_acs_xdslline_upNoiseMarginDb_32days   15
351                         min_dslam_no_counts_7days   14
601                             sum_dslam_inits_1days   14
218                 avg_acs_xdslline_dslUptime_15days   14
144        avg_acs_xdslline_receiveBlocksDelta_32days   14
457        sum_acs_xdslline_transmitBlocksDelta_7days   14
286                            avg_dslam_inits_15days   13
221                 avg_acs_xdslline_cpeUptime_15days   13
220                 min_acs_xdslline_dslUptime_15days   13
444                             avg_dslam_inits_7days   13
381                  min_acs_xdslline_cpeUptime_7days   12
429                       sum_dslam_count_cv_ds_7days   12
378                  min_acs_xdslline_dslUptime_7days   12
302        avg_acs_xdslline_receiveBlocksDelta_15days   12
264           max_acs_xdslline_upNoiseMarginDb_15days   12
349                         avg_dslam_no_counts_7days   12
265           min_acs_xdslline_upNoiseMarginDb_15days   12
94               max_acs_xdslline_downPowerDbm_32days   12
617         sum_acs_xdslline_receiveBlocksDelta_1days   12
76               max_acs_xdslline_usedMemoryKb_32days   12
35                         min_dslam_no_counts_32days   12
209                       avg_dslam_sum_ses_us_15days   12
458        avg_acs_xdslline_transmitBlocksDelta_7days   11
616        avg_acs_xdslline_transmitBlocksDelta_1days   11
539                  min_acs_xdslline_cpeUptime_1days   11
222                 max_acs_xdslline_cpeUptime_15days   11
299       sum_acs_xdslline_transmitBlocksDelta_15days   11
534                  avg_acs_xdslline_dslUptime_1days   11
538                  max_acs_xdslline_cpeUptime_1days   11
30                        avg_dslam_avg_snr_ds_32days   11
219                 max_acs_xdslline_dslUptime_15days   11
460         avg_acs_xdslline_receiveBlocksDelta_7days   10
507                         avg_ds